### ISSUE TITLE
 TypeError: only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by pixieDoug** [ToniCreswell/attribute-cVAEGAN#2]
When running in Python 2.7 or 3.6, the array error occurs for line:
---> 19     label = int(label)

In the Python notebook.  Has anyone successfully run this code?

**Comment by ToniCreswell** [comment]
Should be working now. Thanks for pointing this out.

Toni

**Comment by pixieDoug** [comment]
Thanks Toni.  Was posting the error and then making the change but you beat me to it.
