### ISSUE TITLE
torch.FloatTensor constructor received an invalid combination of arguments

### ISSUE THREAD

**Issue by pixieDoug** [ToniCreswell/attribute-cVAEGAN#3]
Running celeba_cvaegan.py from command-line generates this error. Is there a required parameter that's missing?  Looks like most of them are optional when viewing the code.

Prepare data loaders...
31
(202499,) (202499, 64, 64, 3)
[ 0.  1.]
31
Data loaders ready.
Traceback (most recent call last):
  File "celeba_cvaegan.py", line 72, in <module>
    cvae = CVAE(nz=opts.nz, imSize=64, fSize=opts.fSize)
  File "C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\models.py", line 82, in __init__
    self.encLogVar = nn.Linear((fSize * 8) * inSize * inSize, nz)
  File "C:\Users\dougb1102\Anaconda36\lib\site-packages\torch\nn\modules\linear.py", line 41, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (int, float), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: ([31;1mint[0m, [31;1mfloat[0m)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)

**Comment by pixieDoug** [comment]
Anyone else experiencing this error?

**Comment by ToniCreswell** [comment]
Is there not more to the error which says where in the code it occurred?

**Comment by pixieDoug** [comment]
@ToniCreswell Yes. I have updated my original comment to include the full error.

**Comment by ToniCreswell** [comment]
Can you also give your cmd line input?

**Comment by ToniCreswell** [comment]
Ok. Will fix it now.

**Comment by pixieDoug** [comment]
@ToniCreswell Of course!  It's just 'python celeba_cvaegan.py'  No options, just using defaults.

**Comment by ToniCreswell** [comment]
I think it's cause `imSize / (4 **2)` gives a float, should probably be `imSize // (4 **2)` to be safe. I'll check now.

**Comment by ToniCreswell** [comment]
I can run the code with no issues. I cloned it into a new repo and used it with my current dataset. Is it working for you now?

**Comment by pixieDoug** [comment]
@ToniCreswell You're right.  That was it.  Closing the issue and thanks!

**Comment by ToniCreswell** [comment]
Thank you for your feedback -- very much appreciated! Hope you have fun with the models and let me know if there are any other issues. (Hopefully there aren't any).
