### ISSUE TITLE
Expected object of type Variable[torch.LongTensor] but found type Variable[torch.IntTensor] for argument #1 'target'

### ISSUE THREAD

**Issue by pixieDoug** [ToniCreswell/attribute-cVAEGAN#4]
Outputs will be saved to: ../Experiments/celebA_cVAEGAN\Ex_3
C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\models.py:107: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y = F.softmax(self.encY(x.detach()))
Traceback (most recent call last):
  File "celeba_cvaegan.py", line 128, in <module>
    classLoss = class_loss_fn(pred=predY, target=y)
  File "C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\function.py", line 27, in class_loss_fn
    loss = F.nll_loss(pred, target)
  File "C:\Users\dougb1102\Anaconda36\lib\site-packages\torch\nn\functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: Expected object of type Variable[torch.LongTensor] but found type Variable[torch.IntTensor] for argument #1 'target'

**Comment by ToniCreswell** [comment]
Is this a warning and an error? or just a warning? I get the same warning but no error. Can you provide the top of the print out, should look something like this: 

```
Prepare data loaders...

31

(202499,) (202499, 64, 64, 3)

[0 1]

31

Data loaders ready.

using CUDA
```

**Comment by pixieDoug** [comment]
Yeah, it's a warning and error.  Not worried about the softmax warning.  What I'm more concerned about is why I receive the error and you don't.

Prepare data loaders...
31
(202499,) (202499, 64, 64, 3)
[ 0.  1.]
31
Data loaders ready.

 *** NOT USING CUDA ***

CVAE(
  (enc1): Conv2d (3, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc2): Conv2d (64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc3): Conv2d (128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc4): Conv2d (256, 512, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (encLogVar): Linear(in_features=8192, out_features=100)
  (encMu): Linear(in_features=8192, out_features=100)
  (encY): Linear(in_features=8192, out_features=2)
  (dec1): Linear(in_features=102, out_features=8192)
  (dec2): ConvTranspose2d (512, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec2b): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
  (dec3): ConvTranspose2d (256, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec3b): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
  (dec4): ConvTranspose2d (128, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec4b): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
  (dec5): ConvTranspose2d (64, 3, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
)
DISCRIMINATOR(
  (dis1): Conv2d (3, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis2): Conv2d (64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis3): Conv2d (128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis4): Conv2d (256, 512, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis5): Linear(in_features=8192, out_features=1)
)
Outputs will be saved to: ../Experiments/celebA_cVAEGAN\Ex_8
C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\models.py:107: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y = F.softmax(self.encY(x.detach()))
Traceback (most recent call last):
  File "celeba_cvaegan.py", line 128, in <module>
    classLoss = class_loss_fn(pred=predY, target=y)
  File "C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\function.py", line 27, in class_loss_fn
    loss = F.nll_loss(pred, target)
  File "C:\Users\dougb1102\Anaconda36\lib\site-packages\torch\nn\functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: Expected object of type Variable[torch.LongTensor] but found type Variable[torch.IntTensor] for argument #1 'target'

**Comment by ToniCreswell** [comment]
ok, thanks. I see the error. It's to do with the notebook for making the tensor. It may be an older version. I'll just check.

**Comment by pixieDoug** [comment]
@ToniCreswell Are you saying that you believe the error has to do with my version of jupyter notebook?

**Comment by ToniCreswell** [comment]
Not sure yet. I am re-running notebooks. When I run the code my labels have unique values [0,1] while yours have values [0., 1.]. So there is something wrong here. I am re-running the notebooks to find how this might have happened.

**Comment by ToniCreswell** [comment]
The `celeba_cVAEGAN.py` code is equivalent to the `celeba_info_cVAEGAN.py` with `gamma=0`.  `celeba_cVAEGAN.py` was an older version of the code, which uses older modules. I would suggest using the `celeba_info_cVAEGAN.py` while I fix the issue.

**Comment by ToniCreswell** [comment]
I was able to replicate the error and fix it.
`bceLossTest, klLossTest = vae_loss_fn(rec_x=outputs, x=Variable(xTest), mu=outMu, logVar=outLogVar)`

**Comment by pixieDoug** [comment]
Thanks @ToniCreswell I replaced line 213 of celeba_cVAEGAN.py with 
bceLossTest, klLossTest = vae_loss_fn(rec_x=outputs, x=Variable(xTest), mu=outMu, logVar=outLogVar)
but it still throws the same error: 

Outputs will be saved to: ../Experiments/celebA_cVAEGAN\Ex_19
C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\models.py:107: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y = F.softmax(self.encY(x.detach()))
Traceback (most recent call last):
  File "celeba_cvaegan.py", line 128, in <module>
    classLoss = class_loss_fn(pred=predY, target=y)
  File "C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\function.py", line 27, in class_loss_fn
    loss = F.nll_loss(pred, target)
  File "C:\Users\dougb1102\Anaconda36\lib\site-packages\torch\nn\functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: Expected object of type Variable[torch.LongTensor] but found type Variable[torch.IntTensor] for argument #1 'target'

**Comment by ToniCreswell** [comment]
Can you pull all recent changes and then try to run?

**Comment by pixieDoug** [comment]
Absolutely.

**Comment by pixieDoug** [comment]
@ToniCreswell OK.  Still the same error. Maybe it's something in my ver of PyTorch?

**Comment by ToniCreswell** [comment]
Can you re-run the notebook?

**Comment by pixieDoug** [comment]
I did.  I can try it again though.

**Comment by ToniCreswell** [comment]
> @ToniCreswell OK. Still the same error. Maybe it's something in my ver of PyTorch?

I just reinstalled PyTorch on Mac and re-ran everything (inc notebook) -- everything looked fine.

I also ran using an older version of PyTorch on an server running Ubuntu -- also fine.

Are you using iOS or Ubuntu?

**Comment by pixieDoug** [comment]
Windows pytorch, python 3.6.  Let me place everything on my mac and try.

**Comment by ToniCreswell** [comment]
I am using python 2.7

**Comment by pixieDoug** [comment]
So, I brought everything over to 3.6.  It runs on macOS, but the error surfaces on the Windows machine using the exact same code so must be something in Windows ver of pytorch. I will investigate. Thanks @ToniCreswell Would you like me to close this issue as it's specific to pytorch windows?

**Comment by ToniCreswell** [comment]
Yes please. :D

**Comment by pixieDoug** [comment]
This is a specific error running on Windows due to the dataset returning a numpy data type (np.intc?), which has implementation dependent sizes.  A couple of ways to fix, but in the areas where LongTensor is expected, I changed the attribute to .long()  so:

line 128:  classLoss = class_loss_fn(pred=predY, target=y.long())  
line 214: classScoreTest = torch.eq(predLabel, yTest.long()).float().sum()/yTest.size(0)

**Comment by ToniCreswell** [comment]
Thanks @pixieDoug!

**Comment by pixieDoug** [comment]
Thanks @ToniCreswell Great model!! 

Q: the experiment results you posted, are those based on the default parameters in celeba_cVAEGAN?

**Comment by ToniCreswell** [comment]
No. They are based on parameters in the paper. The opts file for the experiment looks like this:
``` 
 alpha=0.2
 batchSize=32
 beta=0.0
 comments=None
 commit='d8852175c3'
 delta=0.1
 evalMode=False
 fSize=32
 gamma=1.0
 label='Smiling'
 load_VAE_from=None
 lr=0.0002
 maxEpochs=45
 mom=0.5
 nz=200
 outDir='../../Experiments/celebA_info_cVAEGAN'
 rho=0.1
 root='/data/datasets/LabelSwap'
 weightDecay=0.01
```

**Comment by pixieDoug** [comment]
@ToniCreswell In the paper, you site two other attribute tests: male/not male and eye glasses/not eyeglasses.  When experimenting, did you leave your parameter options as outlined above, the same for all three experiments in the paper?

**Comment by ToniCreswell** [comment]
Glasses `opts.txt`

```
alpha=0.1
 batchSize=32
 beta=0.0
 comments=None
 commit='4b1944b18cd'
 delta=0.1
 evalMode=False
 fSize=32
 gamma=1.0
 label='Eyeglasses'
 load_CLASSER_from='../../Experiments_delta_z/celeba_joint_VAE_DZ/Ex_15'
 load_VAE_from=None
 lr=0.0002
 maxEpochs=10
 mom=0.5
 nz=200
 outDir='../../Experiments/celebA_info_cVAEGAN'
 rho=0.1
 root='/data/datasets/LabelSwap'
 weightDecay=0.01
```

**Comment by ToniCreswell** [comment]
Gender `opts.txt`

```
alpha=0.2
 batchSize=32
 beta=1.0
 comments=None
 commit='4b1944b18cd'
 delta=0.1
 evalMode=False
 fSize=32
 gamma=1.0
 label='Male'
 load_CLASSER_from='../../Experiments_delta_z/celeba_joint_VAE_DZ/Ex_15'
 load_VAE_from=None
 lr=0.0002
 maxEpochs=18
 mom=0.5
 nz=200
 outDir='../../Experiments/celebA_info_cVAEGAN'
 rho=0.1
 root='/data/datasets/LabelSwap'
 weightDecay=0.01
```

**Comment by pixieDoug** [comment]
Very interesting. With the exception of the change in the beta value (male/not male), only slight modifications. As always, thanks @ToniCreswell

**Comment by ToniCreswell** [comment]
These are the values to get the results in the paper...however in general it's quite robust to hyper params. Large beta values can lead to artefacts, but can also help the decoder learn more about the attribute you want to edit.
