### ISSUE TITLE
Value cannot be converted to type double without overflow: inf

### ISSUE THREAD

**Issue by pixieDoug** [ToniCreswell/attribute-cVAEGAN#5]
Running 'python celeba_info_cvaegan.py returns:

Prepare data loaders...
31
(202499,) (202499, 64, 64, 3)
[ 0.  1.]
31
Data loaders ready.

 *** NOT USING CUDA ***

CVAE1(
  (enc1): Conv2d (3, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc2): Conv2d (64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc3): Conv2d (128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (enc4): Conv2d (256, 512, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (encLogVar): Linear(in_features=8192, out_features=100)
  (encMu): Linear(in_features=8192, out_features=100)
  (encY): Linear(in_features=8192, out_features=1)
  (dec1): Linear(in_features=101, out_features=8192)
  (dec2): ConvTranspose2d (512, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec2b): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
  (dec3): ConvTranspose2d (256, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec3b): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
  (dec4): ConvTranspose2d (128, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
  (dec4b): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
  (dec5): ConvTranspose2d (64, 3, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
)
DISCRIMINATOR(
  (dis1): Conv2d (3, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis2): Conv2d (64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis3): Conv2d (128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis4): Conv2d (256, 512, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  (dis5): Linear(in_features=8192, out_features=1)
)
AUX(
  (aux1): Linear(in_features=100, out_features=1000)
  (aux2): Linear(in_features=1000, out_features=1000)
  (aux3): Linear(in_features=1000, out_features=1)
)
Outputs will be saved to: ../Experiments/celebA_cVAEGAN\Ex_21
Traceback (most recent call last):
  File "celeba_info_cvaegan.py", line 222, in <module>
    bceLoss, klLoss = cvae.loss(rec_x=outRec, x=x, mu=outMu, logVar=outLogVar)
  File "C:\Users\dougb1102\Documents\Machine Learning models\Pytorch_VAE\code\models.py", line 258, in loss
    KL = 0.5 * torch.sum(mu ** 2 + torch.exp(logVar) - 1. - logVar) #0.5 * sum(1 + log(var) - mu^2 - var)
RuntimeError: value cannot be converted to type double without overflow: inf

Sorry @ToniCreswell Not trying to bring work on you.  Just want to test your model properly.

**Comment by ToniCreswell** [comment]
use a smaller lr: lr=2e-4. I update the default in the last commit.

This error has appeared else where in pyTorch forums. The solutions I have seen is to use smaller lr. For my models I used 2e-4, and recently updated the default to be 2e-4.

You can run code with `--lr=1e-4`

**Comment by pixieDoug** [comment]
Ah!  OK.  I'll lower my learningrate
