### ISSUE TITLE
unsupported operand type(s) for %: 'NoneType' and 'tuple'

### ISSUE THREAD

**Issue by pixieDoug** [ToniCreswell/attribute-cVAEGAN#6]
When running 'python celeba_info_cvaegan.py --lr=1e-4 returns error:

Outputs will be saved to: ../Experiments/celebA_cVAEGAN\Ex_29
[%d, %d] loss: %0.5f, gen: %0.5f, dis: %0.5f, bce: %0.5f, kl: %0.5f, aux: %0.5f, time: %0.3f
Traceback (most recent call last):
  File "celeba_info_cvaegan.py", line 291, in <module>
    (e, i, epochLoss/i, epochLoss_dis/i, epochLoss_gen/i, epochLoss_bce/i, epochLoss_kl/i, epochLoss_aux/i, time() - TIME)
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'

**Comment by ToniCreswell** [comment]
you pasted the old issue here too? can you just put the unsupported operand type(s) for %: 'NoneType' and 'tuple' error in this issue. I do not get this error. You are running: `python celeba_cVAEGAN.py --lr=1e-4` ?

**Comment by pixieDoug** [comment]
Sorry.  I hastily placed all of the return here. I have updated my original comment. I get the error when I run python celeba_info_cvaegan.py --lr=1e-4

**Comment by pixieDoug** [comment]
As this error only occurs with Windows PyTorch, I am closing this issue.
