### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by peitseyang** [ToniCreswell/attribute-cVAEGAN#7]
Hello, thanks for the reply! There are some questions while studying your paper and code.
1. I followed your step and ran the code, but I didn't get the result as the example results rec_0 and rec_1 (I mean smile and no_smile), the two pictures seems the same. I'm not sure what am I missing.
2. What is the difference between celeba_cVAEGAN.py and celeba_info_cVAEGAN.py?

rec_0
![rec_0](https://user-images.githubusercontent.com/38715470/47891003-653bb680-de8c-11e8-9348-d4e04a1fdaf3.png)
rec_1
![rec_1](https://user-images.githubusercontent.com/38715470/47891004-65d44d00-de8c-11e8-9e4b-9f6506f373a0.png)

**Comment by ToniCreswell** [comment]
Hi,

Thanks for your message. Which model did you use? It looks like you used the celeba_cVAEGAN, you need to use the celeba_info_cVAEGAN. 

Also... I'll release a new version soon that gives better visual quality. :)

Let me know if you have any other problems.

Thanks,
Toni.

**Comment by ToniCreswell** [comment]
The difference is explained here: https://arxiv.org/pdf/1711.05175.pdf

**Comment by peitseyang** [comment]
Thank you, I'll try it and go through your paper again!

By the way, I get an error at celeba_info_cVAEGAN.py line : 175, I think it's just a small error for printing:)

**Comment by ToniCreswell** [comment]
Whoops, not sure how that was introduced. Should be fixed now.

**Comment by peitseyang** [comment]
Yep, you get it, haha!

**Comment by ToniCreswell** [comment]
Thanks for your help. :)

**Comment by peitseyang** [comment]
Thank you very much!
I’m looking forward to your new version!!

**Comment by peitseyang** [comment]
Hi,
there is a mistake at your celeba_info_cVAEGAN.py, the printing code after each epoch, I think the dis and gen loss are reversed?

**Comment by ToniCreswell** [comment]
Hi, 

Thanks for pointing this out. I have updated the code.

Thanks, 
Toni.
